### PR TITLE
Replace Travis with GitHub Workflow; add PHP 8; drop PHP 7.1, 7.2

### PR DESCRIPTION
**Pull request by andrewmy**
CI runs here: https://github.com/andrewmy/amqp-interop/pull/1

### CODE REVIEW

**Comment by andrewmy** [comment]
The CI is green on my side. @makasim mind merging this and releasing?

**Comment by makasim** [comment]
Could you add trigger pipeline on commit or merge ?

**Comment by makasim** [comment]
Now, it runs only on PR

**Comment by andrewmy** [comment]
Added a `push` trigger, the closest to what you mean probably

**Comment by makasim** [comment]
https://github.com/queue-interop/amqp-interop/releases/tag/0.8.2

**Comment by makasim** [comment]
Thanks @andrewmy

**Pull request merged**
